'use client'
import { useState } from 'react'
import { supabase } from '../../lib/supabase'

export default function SubscribePage() {
  const [loading, setLoading] = useState(false)
    const [message, setMessage] = useState('')

      const plans = [
          {
                name: 'Monthly Plan',
                      price: '₹999',
                            period: 'per month',
                                  description: 'Full access, monthly draw entry, charity contribution',
                                        type: 'monthly'
                                            },
                                                {
                                                      name: 'Yearly Plan',
                                                            price: '₹9,999',
                                                                  period: 'per year',
                                                                        description: 'Save 2 months, full access, priority draw entry',
                                                                              type: 'yearly'
                                                                                  }
                                                                                    ]

                                                                                      const handleSubscribe = async (planType) => {
                                                                                          setLoading(true)
                                                                                              setMessage('')

                                                                                                  try {
                                                                                                        // Get current user
                                                                                                              const { data: { user } } = await supabase.auth.getUser()

                                                                                                                    if (!user) {
                                                                                                                            setMessage('Please login first')
                                                                                                                                    setLoading(false)
                                                                                                                                            return
                                                                                                                                                  }

                                                                                                                                                        // Create order via API
                                                                                                                                                              const response = await fetch('/api/create-order', {
                                                                                                                                                                      method: 'POST',
                                                                                                                                                                              headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                      body: JSON.stringify({
                                                                                                                                                                                                plan: planType,
                                                                                                                                                                                                          userId: user.id,
                                                                                                                                                                                                                    email: user.email
                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                  })

                                                                                                                                                                                                                                        const order = await response.json()

                                                                                                                                                                                                                                              // Load Cashfree checkout
                                                                                                                                                                                                                                                    const cashfree = await import('@cashfreepayments/cashfree-js')
                                                                                                                                                                                                                                                          const cf = await cashfree.load({ mode: 'sandbox' })

                                                                                                                                                                                                                                                                cf.checkout({
                                                                                                                                                                                                                                                                        paymentSessionId: order.payment_session_id,
                                                                                                                                                                                                                                                                                returnUrl: `${window.location.origin}/payment-success`
                                                                                                                                                                                                                                                                                      })

                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                setMessage('Payment failed. Try again.')
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                        setLoading(false)
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                <main style={{
                                                                                                                                                                                                                                                                                                                      background: '#0a0a0a',
                                                                                                                                                                                                                                                                                                                            minHeight: '100vh',
                                                                                                                                                                                                                                                                                                                                  padding: '60px 20px',
                                                                                                                                                                                                                                                                                                                                        color: 'white',
                                                                                                                                                                                                                                                                                                                                              fontFamily: 'sans-serif'
                                                                                                                                                                                                                                                                                                                                                  }}>
                                                                                                                                                                                                                                                                                                                                                        <h1 style={{
                                                                                                                                                                                                                                                                                                                                                                textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                        fontSize: '36px',
                                                                                                                                                                                                                                                                                                                                                                                color: '#22c55e',
                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: '12px'
                                                                                                                                                                                                                                                                                                                                                                                              }}>
                                                                                                                                                                                                                                                                                                                                                                                                      Choose Your Plan
                                                                                                                                                                                                                                                                                                                                                                                                            </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{
                                                                                                                                                                                                                                                                                                                                                                                                                          textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                  color: '#aaa',
                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: '48px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Subscribe to enter monthly draws and support your chosen charity
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: '24px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flexWrap: 'wrap'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {plans.map(plan => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={plan.type} style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: '#1a1a1a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: '1px solid #333',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: '16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '40px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: '280px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    textAlign: 'center'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 style={{ color: '#22c55e', fontSize: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {plan.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: '48px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          margin: '20px 0 4px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {plan.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ color: '#aaa', marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {plan.period}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ color: '#ccc', marginBottom: '32px', fontSize: '14px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {plan.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => handleSubscribe(plan.type)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: '14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: '#22c55e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: 'black',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: '8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: '16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: 'pointer'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? 'Processing...' : `Subscribe ${plan.name}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: '24px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: '#f87171'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }